site_name: "Combinator.ml"
theme:
  name: material
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
repo_url: https://github.com/combinator-ml/website
nav:
  - Components:
    - components/introduction.md
    - Data:
      - components/data/minio.md
      - components/data/pachyderm.md
      - components/data/feast.md
  - Stacks:
    - stacks/introduction.md
    - stacks/bodywork-mlflow.md
    - stacks/kubeflow-mlflow.md
    - stacks/minio-pachyderm.md
  - design.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
